Repository hmcts/idam-web-public, pull requests merged in 2019-10, with the labels that each got.

#221 Include 1.4.1 changes in preview
  src/main/webapp/WEB-INF/jsp/contactus.jsp
  src/main/webapp/WEB-INF/tags/wrapper.tag
Labels: ready for review

#224 [PREVIEW] SIDM-2862 Create Password fix
  src/main/resources/messages.properties
Labels: ready for review

#226 [PREVIEW] fixed uplift register link
  package-lock.json
  src/main/webapp/WEB-INF/jsp/upliftRegister.jsp
  src/test/js/shared/idam_helper.js
  src/test/js/uplift_user_test.js
Labels: ready for review

#229 [PREVIEW] SIDM-3147 fix cve check
  dependency-check-suppressions.xml
Labels: ready for review

#228 [PREVIEW] SIDM-2856 Link expired screens
  build.gradle
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/UserController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/MvcKeys.java
  src/main/resources/messages.properties
  src/main/webapp/WEB-INF/jsp/expiredActivationLink.jsp
  src/main/webapp/WEB-INF/jsp/expiredPasswordResetLink.jsp
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/UserControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestHelper.java
  src/test/js/expired_links_test.js
Labels: ready for review

#230 [PREVIEW] SIDM-3159 PolicyService: add x-forwarded-for header
  src/main/java/uk/gov/hmcts/reform/idam/web/strategic/PolicyService.java
  src/test/java/uk/gov/hmcts/reform/idam/web/strategic/PolicyServiceTest.java
Labels: ready for review

#231 [PREVIEW] SIDM-3159 ip sanitise
  src/main/java/uk/gov/hmcts/reform/idam/web/strategic/PolicyService.java
  src/test/java/uk/gov/hmcts/reform/idam/web/strategic/PolicyServiceTest.java
Labels: ready for review

#236 chore(security suppression): add jackson-databind CVE-2019-17531
  dependency-check-suppressions.xml
Labels: ready for review

#235 refactor(spring profiles): remove duplication from docker profile
  src/main/resources/application-docker.yaml
  src/main/resources/application.yaml
Labels: ns:idam-web-public-pr-235, ready for review

#237 chore(chart-java): update base chart to 2.11.1
  .gitignore
  Jenkinsfile_CNP
  charts/idam-web-public/Chart.yaml
  charts/idam-web-public/requirements.yaml
  charts/idam-web-public/values.preview.template.yaml
  charts/idam-web-public/values.yaml
Labels: ns:idam-web-public-pr-237, ready for review

#240 [PREVIEW] SIDM-3323 Call authorize only if policy check passes
  Jenkinsfile_CNP
  charts/idam-web-public/Chart.yaml
  charts/idam-web-public/values.preview.template.yaml
  charts/idam-web-public/values.yaml
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
Labels: ns:idam-web-public-pr-240, ready for review

#234 SIDM- 3231 Update headers for authorization iss response
  build.gradle
  src/main/java/uk/gov/hmcts/reform/idam/web/config/properties/StrategicConfigurationProperties.java
  src/main/java/uk/gov/hmcts/reform/idam/web/strategic/SPIService.java
  src/main/resources/application.yaml
Labels: ns:idam-web-public-pr-234

#241 chore(service urls): set urls to their defaults
  Jenkinsfile_CNP
  charts/idam-web-public/Chart.yaml
  charts/idam-web-public/values.preview.template.yaml
  charts/idam-web-public/values.yaml
Labels: ns:idam-web-public-pr-241

#242 Sidm 3073 expand test data deletion
  package-lock.json
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/config/test_data.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/policy_check_functional_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/custom_steps.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/random_data.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
Labels: ns:idam-web-public-pr-242

#247 SIDM 3302 Professional t&cs
  src/main/webapp/WEB-INF/jsp/tandc.jsp
Labels: ns:idam-web-public-pr-247, ready for review
