Repository hmcts/idam-web-public, pull requests merged in 2020-01, with the labels that each got.

#303 SIDM 3487 suspended users login message
  build.gradle
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
Labels: ns:idam-web-public-pr-303

#304 SIDM-3591 Update Contact Us page with email details for SSCS.
  src/main/webapp/WEB-INF/jsp/contactus.jsp
Labels: ns:idam-web-public-pr-304

#309 Bringing all project dependencies in line for 1.5.1.
  build.gradle
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
Labels: ns:idam-web-public-pr-309

#305 Sidm 3557 nightly functional tests
  Jenkinsfile_nightly
Labels: ns:idam-web-public-pr-305

#310 Sidm 3598 password reset with diff case
  src/test/js/reset_password_test.js
Labels: ns:idam-web-public-pr-310

#311 Moving the sonar setup here to be in line with idam-api
  build.gradle
Labels: ns:idam-web-public-pr-311

#312 Sidm 3118 fix flapping tests
  codecept.conf.js
  package-lock.json
  package.json
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/policy_check_functional_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/custom_steps.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  yarn.lock
Labels: ns:idam-web-public-pr-312
