Repository hmcts/idam-web-public, pull requests merged in 2020-12, with the labels that each got.

#544 V5.1 into master
  package.json
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/UserController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/MvcKeys.java
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/expiredcode.jsp
  src/main/webapp/WEB-INF/jsp/useractivation.jsp
  src/main/webapp/WEB-INF/jsp/verification.jsp
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/UserControllerTest.java
  src/test/js/mfa_e2e_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-544

#545 SIDM-5176: Ensure we don't lose nonce and prompt again
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/webapp/WEB-INF/jsp/expiredcode.jsp
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-545

#546 SIDM-5241: Updating working hours for OCMC on the Contact page.
  build.gradle
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/contactus.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-546

#328 SIDM-5259 Removing the swagger ui dependencies
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-328

#550 Address CVE-2020-8908
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-550

#551 Sidm 5237 tests
  src/test/js/mfa_e2e_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-551

#552 SIDM-3703 apostrophe email reset password test
  src/test/js/reset_password_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-552

#555 suppress CVE errors
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-555

#553 add IE in cross browser list
  saucelabs.conf.js
  src/test/js/config/supportedBrowsers.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-553
