Repository hmcts/idam-web-public, pull requests merged in 2021-05, with the labels that each got.

#605 Successful jitpack local build
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-605

#606 SIDM-5763 Revert "SIDM-5718: Disable reset password button on click"
  src/main/webapp/WEB-INF/jsp/resetpassword.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-606

#616 IDAM v5.3.0
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  build.gradle
  charts/idam-web-public/Chart.yaml
  charts/idam-web-public/values.yaml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  rules-pmd.xml
  src/main/resources/application-docker.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
  src/main/webapp/WEB-INF/jsp/resetpassword.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-616

#618 SIDM-5834 update pitest
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-618

#617 fix reset password test issues
  src/test/js/reset_password_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-617

#619 SIDM-5834 update pitest (#618)
  build.gradle
  src/test/js/reset_password_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-619

#620 Build using master jenkins branch
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  README.md
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-620

#623 Sidm 5860 refactor tests with random prefix
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/random_data.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-623
