Repository hmcts/idam-web-public, pull requests merged in 2021-03, with the labels that each got.

#580 fix crossbrowser tests and zap scanner issues
  Jenkinsfile_nightly
  audit.json
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-580

#579 Preview 5.3
  build.gradle
  package-lock.json
  package.json
  saucelabs.conf.js
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/config/supportedBrowsers.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/expired_links_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/oidc_endpoints_through_webpublic_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/custom_steps.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/sauceLabsReportingHelper.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-579

#581 fix stale user journey tests
  src/test/js/mfa_e2e_test.js
  src/test/js/stale_user_login_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-581

#582 fix-cves
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-582

#583 Fix CVE
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-583

#584 update audit.json file with false positives
  audit.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-584

#585 fix flaky tests
  src/test/js/stale_user_login_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-585

#574 SIDM-5405 Address CVEs
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  build.gradle
  charts/idam-web-public/Chart.yaml
  charts/idam-web-public/requirements.yaml
  charts/idam-web-public/values.yaml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  rules-pmd.xml
  src/main/resources/application-docker.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-574

#591 SIDM-5622: Upgrade netty to address CVE-2021-21295
  build.gradle
  charts/idam-web-public/values.preview.template.yaml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-591

#592 SIDM-5638: Codecept3 and other test setup updates
  build.gradle
  package-lock.json
  package.json
  saucelabs.conf.js
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/config/supportedBrowsers.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/expired_links_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/oidc_endpoints_through_webpublic_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/custom_steps.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/sauceLabsReportingHelper.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-592
