Repository hmcts/idam-web-public, pull requests merged in 2021-02, with the labels that each got.

#567 Content update to Contact-Us page
  audit.json
  build.gradle
  dependency-check-suppressions.xml
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/contactus.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-567

#568 Sidm 5413 codecept3 crossbrowser tests
  package.json
  saucelabs.conf.js
  src/test/js/config/supportedBrowsers.js
  src/test/js/cross_browser_test.js
  src/test/js/shared/sauceLabsReportingHelper.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-568

#570 improve functional tests
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/expired_links_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/custom_steps.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-570

#571 SIDM-5420: CTSC change in contact details - combined for English and Welsh speakers
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/config/properties/ConfigurationProperties.java
  src/main/java/uk/gov/hmcts/reform/idam/web/config/properties/FeaturesConfigurationProperties.java
  src/main/resources/application.yaml
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/contactus.jsp
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-571

#573 extend mfa step up e2e tests
  src/test/js/mfa_e2e_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-573

#577 upgrade netty
  audit.json
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-577

#578 Fix invalid cookie mfa tests
  src/test/js/mfa_e2e_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-578
