Repository hmcts/idam-web-public, pull requests merged in 2021-07, with the labels that each got.

#662 SIDM-6005 Actually open in new tab
  src/main/webapp/WEB-INF/jsp/cookiePreferences.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-662

#661 SIDM-5279 Handle duplicate accounts in uplift login
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-661

#663 suppress zap scanner issues
  audit.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-663

#664 SIDM-6003 Make stale user error not a link
  src/main/resources/static/assets/stylesheets/govuk-template.css
  src/main/webapp/WEB-INF/jsp/staleUserResetPassword.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-664

#666 SIDM-5280 fix error message
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-666

#665 5.3.3 rc1 to master
  README.md
  codecept.conf.js
  functional-output/screenshots/base/Polycheck-login.png
  functional-output/screenshots/base/create-newpassword.png
  functional-output/screenshots/base/mfa-verification.png
  functional-output/screenshots/base/password-changed.png
  functional-output/screenshots/base/reset-password.png
  functional-output/test
  package.json
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/config/IdamWebMvcConfiguration.java
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/MvcKeys.java
  src/main/resources/static/assets/stylesheets/govuk-template.css
  src/main/webapp/WEB-INF/jsp/cookiePreferences.jsp
  src/main/webapp/WEB-INF/jsp/index.jsp
  src/main/webapp/WEB-INF/jsp/resetpassword.jsp
  src/main/webapp/WEB-INF/jsp/staleUserResetPassword.jsp
  src/main/webapp/WEB-INF/jsp/upliftLogin.jsp
  src/main/webapp/WEB-INF/jsp/useractivation.jsp
  src/main/webapp/WEB-INF/tags/wrapper.tag
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/uplift_user_test.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-665

#653 Add zap scanner suppressions
  audit.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-653

#667 SIDM-5280
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/UserController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/model/ForgotPasswordRequest.java
  src/main/java/uk/gov/hmcts/reform/idam/web/model/RegisterUserRequest.java
  src/main/java/uk/gov/hmcts/reform/idam/web/model/UpliftRequest.java
  src/main/webapp/WEB-INF/jsp/forgotpasswordsuccess.jsp
  src/main/webapp/WEB-INF/jsp/login.jsp
  src/main/webapp/WEB-INF/jsp/selfRegister.jsp
  src/main/webapp/WEB-INF/jsp/staleUserResetPassword.jsp
  src/main/webapp/WEB-INF/jsp/upliftLogin.jsp
  src/main/webapp/WEB-INF/jsp/upliftRegister.jsp
  src/main/webapp/WEB-INF/jsp/usercreated.jsp
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-667

#668 Sidm 5279 enhance uplift register functional tests
  src/test/js/uplift_user_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-668

#671 remove pa11y suppressions
  pa11y.conf.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-671

#672 SIDM-6043 Updating the cookie-manager.js
  src/main/resources/static/assets/javascripts/cookie-manager.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-672

#674 SIDM-6045: Upgrade json-smart to resolve CVE-2021-27568
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-674

#675 SIDM-6045: Resolve CVE-2021-27568
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-675

#676 Sidm 6044 fix intermittent tests
  codecept.conf.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-676

#677 SIDM-6067 Update Customer Service e-mail
  src/main/resources/messages.properties
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-677

#678 Address CVE-2021-33037
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-678

#679 Address CVE-2021-33037
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-679

#681 Sidm 6063 idam 540
  audit.json
  build.gradle
  codecept.conf.js
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/UserController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/model/ForgotPasswordRequest.java
  src/main/java/uk/gov/hmcts/reform/idam/web/model/RegisterUserRequest.java
  src/main/java/uk/gov/hmcts/reform/idam/web/model/UpliftRequest.java
  src/main/resources/messages.properties
  src/main/webapp/WEB-INF/jsp/forgotpasswordsuccess.jsp
  src/main/webapp/WEB-INF/jsp/login.jsp
  src/main/webapp/WEB-INF/jsp/selfRegister.jsp
  src/main/webapp/WEB-INF/jsp/staleUserResetPassword.jsp
  src/main/webapp/WEB-INF/jsp/upliftLogin.jsp
  src/main/webapp/WEB-INF/jsp/upliftRegister.jsp
  src/main/webapp/WEB-INF/jsp/usercreated.jsp
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/uplift_user_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-681

#680 Add fortify to pipeline
  .gitignore
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
  config/sub-directory-spring-workaround/empty.file
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-680

#682 exclude and tidy up zap scanner issues
  audit.json
  zap-exclusions
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-682

#683 SIDM-6016 adding org mfa tests
  codecept.conf.js
  src/test/js/config/test_data.js
  src/test/js/mfa_org_e2e_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/refdata_helper.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-683

#685 add org mfa test urls
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-685
