Repository hmcts/idam-web-public, pull requests merged in 2021-10, with the labels that each got.

#716 add cookie banner test steps
  src/test/js/login_user_functional_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-716

#715 SIDM-6348 disable redis health check
  src/main/resources/application.yaml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-715

#721 SIDM-6455 Redirect SSO users to their IdP login page
  build.gradle
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/strategic/ApiAuthResult.java
  src/main/java/uk/gov/hmcts/reform/idam/web/strategic/SPIService.java
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-721
