Repository hmcts/idam-web-public, pull requests merged in 2021-01, with the labels that each got.

#557 upgrade netflix servo only
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-557

#558 Sidm 5312 tests refactor
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/reset_password_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-558

#560 SIDM-5329 remove inactive CVE suppressions
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-560

#561 update bom version
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-561

#562 Sidm 5340 improve notify emails fetching
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-562

#564 OWASP ZAP false positive: Timestamp Disclosure - Unix
  audit.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-564

#563 SIDM-5390 Use codecept3 and update other node package versions
  build.gradle
  package-lock.json
  package.json
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/expired_links_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/oidc_endpoints_through_webpublic_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-563
