Repository hmcts/idam-web-public, pull requests merged in 2021-08, with the labels that each got.

#687 SIDM-6136: Upgrade helm chart-java to latest
  charts/idam-web-public/Chart.yaml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-687

#688 add mfa org tests
  src/test/js/mfa_org_e2e_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-688

#686 SIDM-6131: Updates to the content of the Verification code screen.
  .gitignore
  Jenkinsfile_nightly
  build.gradle
  charts/idam-web-public/Chart.yaml
  config/fortify-client.properties
  config/sub-directory-spring-workaround/empty.file
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/verification.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-686

#690 SIDM-6048: Fix for adding fortify scan stage to nightly master pipeline
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-690

#691 SIDM-6178: Fix contact-us links
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-691

#693 Preview to Master
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  codecept.conf.js
  src/test/js/config/test_data.js
  src/test/js/mfa_org_e2e_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/refdata_helper.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-693

#694 Suppress false positive
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-694

#695 update waitForAction timeout config
  codecept.conf.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-695

#697 SIDM-6242 Enable sync branch with master
  Jenkinsfile_CNP
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-697
