Repository hmcts/idam-web-public, pull requests merged in 2022-04, with the labels that each got.

#759 Add automated jira tickets to nightly pipeline
  Jenkinsfile_nightly
  build.gradle
  gradle/jira.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-759

#774 IDAM 7.5.0-RC to master
  Jenkinsfile_nightly
  build.gradle
  dependency-check-suppressions.xml
  gradle/jira.gradle
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/UserController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/error/CustomErrorController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/MvcKeys.java
  src/main/java/uk/gov/hmcts/reform/idam/web/model/ForgotPasswordRequest.java
  src/main/java/uk/gov/hmcts/reform/idam/web/model/SelfRegisterRequest.java
  src/main/java/uk/gov/hmcts/reform/idam/web/strategic/EndSessionFilter.java
  src/main/webapp/WEB-INF/jsp/expiredcode.jsp
  src/main/webapp/WEB-INF/jsp/forgotpassword.jsp
  src/main/webapp/WEB-INF/jsp/forgotpasswordsuccess.jsp
  src/main/webapp/WEB-INF/jsp/login.jsp
  src/main/webapp/WEB-INF/jsp/selfRegister.jsp
  src/main/webapp/WEB-INF/jsp/staleUserResetPassword.jsp
  src/main/webapp/WEB-INF/jsp/upliftLogin.jsp
  src/main/webapp/WEB-INF/jsp/usercreated.jsp
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/UserControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/error/CustomErrorControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/strategic/EndSessionFilterTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/strategic/SPIServiceTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestHelper.java
  src/test/js/ejudiciary_login_test.js
  src/test/js/end_session_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/moj_login_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/uplift_user_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-774

#776 SIDM-7495 Old spring artifact CVE
  dependency-check-suppressions.xml
  gradle/jira.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-776

#777 SIDM-7509 Dependency check issues
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-777
