Repository hmcts/idam-web-public, pull requests merged in 2022-10, with the labels that each got.

#819 SIDM-8132: Address CVE-2022-38752
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-819

#820 SIDM-8132: Address CVE-2022-38752
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-820

#821 SIDM-8141: Upgrade jackson databind to address CVE-2022-42004
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-821

#824 SIDM-8081 Change in Monarchy
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/MvcKeys.java
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/tacticalActivateExpired.jsp
  src/main/webapp/WEB-INF/jsp/tacticalResetPassword.jsp
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-824
