Repository hmcts/idam-web-public, pull requests merged in 2022-01, with the labels that each got.

#751 add delay after creating service and policy
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/mfa_org_e2e_test.js
  src/test/js/moj_login_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-751

#752 suppress zap scanner issues
  audit.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-752

#755 update sso tests for case insensitive verification
  src/test/js/ejudiciary_login_test.js
  src/test/js/moj_login_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-755

#756 SIDM-6980 fix security vulnerabilities
  build.gradle
  dependency-check-suppressions.xml
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-756

#757 7.2.0 Release Candidate
  build.gradle
  dependency-check-suppressions.xml
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/mfa_org_e2e_test.js
  src/test/js/moj_login_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-757
