Repository hmcts/idam-web-public, pull requests merged in 2022-05, with the labels that each got.

#778 SIDM-7556: Tests: Complete SSO flow before deleting the federated user
  src/test/js/ejudiciary_login_test.js
  src/test/js/moj_login_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-778

#779 SIDM-7545 Adoption contact us
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/contactus.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-779

#783 Added @functional tag to the scenario 'I can set the language with a …
  src/test/js/welsh_language_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-783

#784 SIDM-7523 disable ga
  src/main/webapp/WEB-INF/tags/wrapper.tag
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-784

#785 Fix accessibility issues
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/forgotpassword.jsp
  src/main/webapp/WEB-INF/jsp/login.jsp
  src/main/webapp/WEB-INF/jsp/loginWithPin.jsp
  src/main/webapp/WEB-INF/jsp/resetpassword.jsp
  src/main/webapp/WEB-INF/jsp/selfRegister.jsp
  src/main/webapp/WEB-INF/jsp/upliftLogin.jsp
  src/main/webapp/WEB-INF/jsp/upliftRegister.jsp
  src/main/webapp/WEB-INF/jsp/useractivation.jsp
  src/main/webapp/WEB-INF/jsp/verification.jsp
  src/main/webapp/WEB-INF/tags/wrapper.tag
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/cross_browser_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/welsh_constants.js
  src/test/js/uplift_user_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-785

#786 SIDM-7615 bump netty
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-786

#780 refactor to use testing support service
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/config/test_data.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/end_session_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/mfa_org_e2e_test.js
  src/test/js/moj_login_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-780

#787 SIDM-7639: Upgrade to latest bom to upgrade to Spring Boot 2.6.8
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-787

#788 update electron dependancy to support M1 Mac machine
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-788
