Repository hmcts/idam-web-public, pull requests merged in 2022-06, with the labels that each got.

#789 SIDM-7712 - Fix CVE-2022-22976 and CVE-2022-22970
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-789

#790 SIDM-7712 Merge CVE changes from master to preview branch
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-790

#791 SIDM-7712 Suppress CVE-2022-22978
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-791

#793 SIDM-7468 handle failure in federation authenticate
  src/main/java/uk/gov/hmcts/reform/idam/web/sso/SSOAuthenticationSuccessHandler.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-793

#794 IDAM 7.7.0-RC to master
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  package.json
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/sso/SSOAuthenticationSuccessHandler.java
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/webapp/WEB-INF/jsp/contactus.jsp
  src/main/webapp/WEB-INF/jsp/forgotpassword.jsp
  src/main/webapp/WEB-INF/jsp/login.jsp
  src/main/webapp/WEB-INF/jsp/loginWithPin.jsp
  src/main/webapp/WEB-INF/jsp/resetpassword.jsp
  src/main/webapp/WEB-INF/jsp/selfRegister.jsp
  src/main/webapp/WEB-INF/jsp/upliftLogin.jsp
  src/main/webapp/WEB-INF/jsp/upliftRegister.jsp
  src/main/webapp/WEB-INF/jsp/useractivation.jsp
  src/main/webapp/WEB-INF/jsp/verification.jsp
  src/main/webapp/WEB-INF/tags/wrapper.tag
  src/test/java/uk/gov/hmcts/reform/idam/web/AppControllerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/sso/SSOAuthenticationSuccessHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/idam/web/util/TestConstants.java
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/config/test_data.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/end_session_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/mfa_org_e2e_test.js
  src/test/js/moj_login_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/welsh_constants.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-794

#799 Fix cross browser tests
  src/test/js/cross_browser_test.js
  src/test/js/welsh_language_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-799
