Repository hmcts/idam-web-public, pull requests merged in 2023-11, with the labels that each got.

#970 after always
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-970

#892 Use default security.sh for OWASP ZAP scan
  .ci/security.sh
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-892

#1005 Sync nightly-dev with master
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1005

#1007 Fix some code smells
  src/main/java/uk/gov/hmcts/reform/idam/web/AppController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/UserController.java
  src/main/java/uk/gov/hmcts/reform/idam/web/client/OidcApi.java
  src/main/java/uk/gov/hmcts/reform/idam/web/config/OIDCLocaleChangeInterceptor.java
  src/main/java/uk/gov/hmcts/reform/idam/web/health/ApiHealthIndicator.java
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/ErrorHelper.java
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/MvcKeys.java
  src/test/java/uk/gov/hmcts/reform/idam/web/UserControllerTest.java
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1007

#1017 Enable fortify scan by default
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1017
