Repository hmcts/idam-web-public, pull requests merged in 2023-08, with the labels that each got.

#875 Accessibility Statement and Palette update
  dependency-check-suppressions.xml
  src/main/resources/messages.properties
  src/main/resources/messages_cy.properties
  src/main/resources/static/assets/stylesheets/govuk-template-ie6.css
  src/main/resources/static/assets/stylesheets/govuk-template-ie7.css
  src/main/resources/static/assets/stylesheets/govuk-template-ie8.css
  src/main/resources/static/assets/stylesheets/govuk-template.css
  src/main/webapp/WEB-INF/jsp/accessibilityStatement.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-875

#877 Upgrade Spring Boot and clean up dependencies suppressions
  build.gradle
  dependency-check-suppressions.xml
  gradle/libs.versions.toml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-877

#879 Fix mutation tests
  build.gradle
  gradle/libs.versions.toml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-879

#880 Increase the contrast for the link in the old global gov.uk cookies message
  src/main/resources/static/assets/stylesheets/govuk-template-ie6.css
  src/main/resources/static/assets/stylesheets/govuk-template-ie7.css
  src/main/resources/static/assets/stylesheets/govuk-template-ie8.css
  src/main/resources/static/assets/stylesheets/govuk-template.css
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-880

#857 Update Dockerfile
  Dockerfile
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-857
