Repository hmcts/idam-web-public, pull requests merged in 2023-04, with the labels that each got.

#860 Amended Welsh translations on web public screens
  Dockerfile
  src/main/resources/messages_cy.properties
  src/test/js/shared/welsh_constants.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-860

#861 New base java image and removal of security.sh
  Dockerfile
  security.sh
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-861

#864 SIDM-8608: Upgrade Spring Boot to address CVE-2023-20863
  gradle/libs.versions.toml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-864
