Repository hmcts/idam-web-public, pull requests merged in 2023-09, with the labels that each got.

#883 SIDM-8874 Add language tag to switcher
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/JSPHelper.java
  src/main/webapp/WEB-INF/tags/languageSwitch.tag
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-883

#884 Address CVEs
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-884

#887 SIDM-8832 Fix dependency check.
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-887

#886 Update security.sh
  .ci/security.sh
  audit.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-886

#889 Tests fixes
  .ci/security.sh
  src/test/js/shared/idam_helper.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-889

#888 Address CVEs (#884)
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-888

#890 Upgrade owasp dependency check plugin
  gradle/libs.versions.toml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-890

#891 IDAM 9.2.0-RC1
  Dockerfile
  build.gradle
  dependency-check-suppressions.xml
  gradle/libs.versions.toml
  src/main/java/uk/gov/hmcts/reform/idam/web/helper/JSPHelper.java
  src/main/webapp/WEB-INF/tags/languageSwitch.tag
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-891

#894 Create renovate.json
  renovate.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-894

#898 Fix renovate config
  renovate.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-898

#901 Change base branch for renovate PRs
  renovate.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-901
