Repository hmcts/idam-web-public, pull requests merged in 2023-03, with the labels that each got.

#853 Suppress spring 2.7.x vulnerabilities
  build.gradle
  dependency-check-suppressions.xml
  gradle/libs.versions.toml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-853

#855 SIDM-8486: Upgrade libs and plugins
  build.gradle
  dependency-check-suppressions.xml
  gradle/libs.versions.toml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-855

#856 Changes in tests to support ForgeRock 7.2
  src/test/js/moj_login_test.js
  src/test/js/shared/idam_helper.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-856
