Repository hmcts/idam-web-public, pull requests merged in 2023-12, with the labels that each got.

#1022 Ignore ejudiciary tests (until a new SSO app is created)
  src/test/js/ejudiciary_login_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1022

#1027 Update renovate schedule
  renovate.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1027

#1030 Master to Preview
  Jenkinsfile_nightly
  dependency-check-suppressions.xml
  renovate.json
  src/test/js/ejudiciary_login_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1030
