Repository hmcts/idam-web-public, pull requests merged in 2023-06, with the labels that each got.

#868 SIDM-8706- Fix Nightly
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-868

#869 Address CVE-2023-20883
  gradle/libs.versions.toml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-869

#870 IDAM 9.0 RC
  Jenkinsfile_nightly
  src/main/resources/messages_cy.properties
  src/test/js/moj_login_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/welsh_constants.js
  src/test/js/uplift_user_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-870
