Repository hmcts/idam-web-public, pull requests merged in 2024-11, with the labels that each got.

#1293 Revert "Do not use PRD for tests as it is down"
  Jenkinsfile_CNP
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1293

#1299 create users in tests
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1299

#1310 tests throw errors
  src/test/js/moj_login_test.js
  src/test/js/shared/idam_helper.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1310
