Repository hmcts/idam-web-public, pull requests merged in 2024-07, with the labels that each got.

#1182 Address CVE-2023-35116
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1182

#1195 IDAM 9.7.0-RC1
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  charts/idam-web-public/Chart.yaml
  charts/idam-web-public/values.yaml
  gradle/jira.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  package.json
  src/main/webapp/WEB-INF/jsp/forgotpasswordsuccess.jsp
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/config/test_data.js
  src/test/js/cross_browser_test.js
  src/test/js/dynamic_user_registration_test.js
  src/test/js/ejudiciary_login_test.js
  src/test/js/end_session_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/mfa_e2e_test.js
  src/test/js/mfa_org_e2e_test.js
  src/test/js/moj_login_test.js
  src/test/js/reset_password_test.js
  src/test/js/self_registration_test.js
  src/test/js/shared/idam_helper.js
  src/test/js/shared/random_data.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
  src/test/js/user_expiration_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
  src/test/js/user_registration_with_the_same_uuid_in_pending_status_test.js
  src/test/js/welsh_language_test.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1195

#1197 IDAM 9.7.0-RC2
  Jenkinsfile_CNP
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1197

#1199 Fix MOJ login test assertions
  src/test/js/moj_login_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1199

#1200 IDAM 9.7.0-RC3
  src/test/js/moj_login_test.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1200

#1201 SIDM-9199: Fix broken reset password link
  src/main/webapp/WEB-INF/jsp/forgotpasswordsuccess.jsp
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1201

#1205 Fix cross browser tests
  package.json
  src/test/js/account_lockout_reset_password_test.js
  src/test/js/login_user_functional_test.js
  src/test/js/login_user_with_scope_functional_test.js
  src/test/js/shared/custom_steps.js
  src/test/js/uplift_user_test.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1205
