Repository hmcts/idam-web-public, pull requests merged in 2024-08, with the labels that each got.

#1218 SIDM-9373 fix pipelines
  src/test/js/dynamic_user_registration_test.js
  src/test/js/stale_user_login_test.js
  src/test/js/uplift_user_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1218

#1223 SIDM-9347 Fix
  src/test/js/config/test_data.js
  src/test/js/mfa_org_e2e_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1223

#1222 SIDM-9365 Java 21
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1222

#1224 Test fixes
  src/test/js/moj_login_test.js
  src/test/js/user_registration_pending_status_and_post_activation_redirect_url_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1224
