Repository hmcts/idam-web-public, pull requests merged in 2024-01, with the labels that each got.

#1048 SIDM-9034 Renovate schedule
  renovate.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1048

#1053 Change session cleanup to run every day
  src/main/resources/application.yaml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1053

#1054 IDAM 9.5-RC1
  build.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  package.json
  src/main/resources/application.yaml
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1054

#1057 Fix yarn.lock
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1057

#1065 SIDM-9061: An e2e test to cover email-sso-id mismatch in the SSO journey
  src/test/js/moj_login_test.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1065
