Repository hmcts/idam-web-public, pull requests merged in 2024-09, with the labels that each got.

#1232 retry failed tests
  README.md
  codecept.conf.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1232

#1236 Preview retry (merge master)
  README.md
  codecept.conf.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1236

#1239 IDAM 9.8.0-RC1
  Dockerfile
  build.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1239

#1246 Do not use PRD for tests as it is down
  Jenkinsfile_CNP
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1246

#1250 Cross Browser Tests Fix
  Jenkinsfile_nightly
  package.json
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1250

#1258 Cross Browser Fix
  src/test/js/config/supportedBrowsers.js
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1258
