Repository hmcts/idam-web-public, pull requests merged in 2025-06, with the labels that each got.

#1457 Upgrade spring framework to address CVE-2024-22259
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1457

#1466 SIDM-9347 suppressing CVE
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1466

#1456 CME-530 replace jitpack with azure
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-web-public-pr-1456
